#!/usr/bin/env python3
"""
Core Function Verification Script
Generated by Repo Genesis Auditor v2.0

このスクリプトは、リポジトリの存在意義（コア機能）を検証します。
Androidプロジェクトのため、直接実行ではなく構造検証を行います。
"""

import json
import os
import re
import sys
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Any, Optional, List

@dataclass
class VerificationResult:
    function_id: str
    scenario_name: str
    passed: bool
    actual_output: Any
    expected_output: Any
    error_message: Optional[str] = None
    interpretation: str = ""

def get_project_root() -> Path:
    """プロジェクトルートを取得"""
    script_dir = Path(__file__).parent
    return script_dir.parent.parent.parent

def verify_cf001_usage_stats_implementation() -> VerificationResult:
    """
    CF-001: 当日のアプリ別利用時間を取得できる
    
    UsageStatsDataSource.kt の実装を検証
    """
    project_root = get_project_root()
    source_file = project_root / "app/src/main/java/jp/co/screentime/slackreporter/data/usage/UsageStatsDataSource.kt"
    
    if not source_file.exists():
        return VerificationResult(
            function_id="CF-001",
            scenario_name="UsageStats実装の存在確認",
            passed=False,
            actual_output=None,
            expected_output="UsageStatsDataSource.kt が存在",
            error_message=f"ファイルが見つかりません: {source_file}",
            interpretation="利用時間取得機能の実装ファイルが存在しない"
        )
    
    content = source_file.read_text()
    
    # 必須要素のチェック
    checks = [
        ("UsageStatsManager", "UsageStatsManagerの使用"),
        ("queryUsageStats", "統計クエリメソッドの呼び出し"),
        ("totalTimeInForeground", "フォアグラウンド時間の取得"),
        ("AppUsage", "ドメインモデルへの変換"),
    ]
    
    missing = []
    for pattern, description in checks:
        if pattern not in content:
            missing.append(description)
    
    passed = len(missing) == 0
    
    return VerificationResult(
        function_id="CF-001",
        scenario_name="UsageStats実装の検証",
        passed=passed,
        actual_output=f"検出: {len(checks) - len(missing)}/{len(checks)} 要素",
        expected_output="全ての必須要素が実装されている",
        error_message=f"未実装: {missing}" if missing else None,
        interpretation=(
            "利用時間取得機能が正しく実装されている" if passed
            else f"以下の要素が不足: {', '.join(missing)}"
        )
    )

def verify_cf002_slack_webhook_implementation() -> VerificationResult:
    """
    CF-002: Slack Webhookへ送信できる
    
    SlackWebhookClient.kt と SlackWebhookValidator.kt の実装を検証
    """
    project_root = get_project_root()
    
    client_file = project_root / "app/src/main/java/jp/co/screentime/slackreporter/data/slack/SlackWebhookClient.kt"
    validator_file = project_root / "app/src/main/java/jp/co/screentime/slackreporter/data/slack/SlackWebhookValidator.kt"
    
    missing_files = []
    if not client_file.exists():
        missing_files.append("SlackWebhookClient.kt")
    if not validator_file.exists():
        missing_files.append("SlackWebhookValidator.kt")
    
    if missing_files:
        return VerificationResult(
            function_id="CF-002",
            scenario_name="Slack送信実装の存在確認",
            passed=False,
            actual_output=None,
            expected_output="SlackWebhookClient.kt, SlackWebhookValidator.kt が存在",
            error_message=f"ファイルが見つかりません: {missing_files}",
            interpretation="Slack送信機能の実装ファイルが不足"
        )
    
    client_content = client_file.read_text()
    validator_content = validator_file.read_text()
    
    # 必須要素のチェック
    checks = [
        (client_content, "OkHttpClient", "OkHttpクライアントの使用"),
        (client_content, "sendMessage", "メッセージ送信メソッド"),
        (client_content, "application/json", "JSON Content-Type"),
        (validator_content, "hooks.slack.com", "Slack URLの検証"),
        (validator_content, "https", "HTTPS検証"),  # Fixed: check for scheme validation
    ]
    
    missing = []
    for content, pattern, description in checks:
        if pattern not in content:
            missing.append(description)
    
    passed = len(missing) == 0
    
    return VerificationResult(
        function_id="CF-002",
        scenario_name="Slack送信実装の検証",
        passed=passed,
        actual_output=f"検出: {len(checks) - len(missing)}/{len(checks)} 要素",
        expected_output="全ての必須要素が実装されている",
        error_message=f"未実装: {missing}" if missing else None,
        interpretation=(
            "Slack Webhook送信機能が正しく実装されている" if passed
            else f"以下の要素が不足: {', '.join(missing)}"
        )
    )

def verify_cf003_worker_implementation() -> VerificationResult:
    """
    CF-003: 指定時刻に自動でレポートを送信できる
    
    DailySlackReportWorker.kt の実装を検証
    """
    project_root = get_project_root()
    worker_file = project_root / "app/src/main/java/jp/co/screentime/slackreporter/workers/DailySlackReportWorker.kt"
    
    if not worker_file.exists():
        return VerificationResult(
            function_id="CF-003",
            scenario_name="WorkManager Worker実装の存在確認",
            passed=False,
            actual_output=None,
            expected_output="DailySlackReportWorker.kt が存在",
            error_message=f"ファイルが見つかりません: {worker_file}",
            interpretation="定時実行Worker の実装ファイルが存在しない"
        )
    
    content = worker_file.read_text()
    
    # 必須要素のチェック
    checks = [
        ("CoroutineWorker", "CoroutineWorkerの継承"),
        ("@HiltWorker", "Hilt DIアノテーション"),
        ("doWork", "doWorkメソッドの実装"),
        ("Result.success", "成功時の戻り値"),
        ("Result.retry", "リトライ処理"),
        ("sendDailyReportUseCase", "UseCase呼び出し"),
    ]
    
    missing = []
    for pattern, description in checks:
        if pattern not in content:
            missing.append(description)
    
    passed = len(missing) == 0
    
    return VerificationResult(
        function_id="CF-003",
        scenario_name="WorkManager Worker実装の検証",
        passed=passed,
        actual_output=f"検出: {len(checks) - len(missing)}/{len(checks)} 要素",
        expected_output="全ての必須要素が実装されている",
        error_message=f"未実装: {missing}" if missing else None,
        interpretation=(
            "定時実行機能が正しく実装されている" if passed
            else f"以下の要素が不足: {', '.join(missing)}"
        )
    )

def verify_cf004_exclusion_implementation() -> VerificationResult:
    """
    CF-004: 特定のアプリを除外設定できる
    
    SendDailyReportUseCase.kt の除外ロジックを検証
    """
    project_root = get_project_root()
    usecase_file = project_root / "app/src/main/java/jp/co/screentime/slackreporter/domain/usecase/SendDailyReportUseCase.kt"
    
    if not usecase_file.exists():
        return VerificationResult(
            function_id="CF-004",
            scenario_name="除外機能実装の存在確認",
            passed=False,
            actual_output=None,
            expected_output="SendDailyReportUseCase.kt が存在",
            error_message=f"ファイルが見つかりません: {usecase_file}",
            interpretation="日次レポート送信UseCase が存在しない"
        )
    
    content = usecase_file.read_text()
    
    # 除外ロジックのチェック
    checks = [
        ("excludedPackages", "除外パッケージ設定の参照"),
        ("filter", "フィルタリング処理"),
        ("!in", "除外判定ロジック"),
    ]
    
    missing = []
    for pattern, description in checks:
        if pattern not in content:
            missing.append(description)
    
    passed = len(missing) == 0
    
    return VerificationResult(
        function_id="CF-004",
        scenario_name="除外機能実装の検証",
        passed=passed,
        actual_output=f"検出: {len(checks) - len(missing)}/{len(checks)} 要素",
        expected_output="全ての除外ロジック要素が実装されている",
        error_message=f"未実装: {missing}" if missing else None,
        interpretation=(
            "除外アプリ設定機能が正しく実装されている" if passed
            else f"以下の要素が不足: {', '.join(missing)}"
        )
    )

def verify_cf005_manual_send_implementation() -> VerificationResult:
    """
    CF-005: 手動でも送信できる
    
    HomeViewModel と SendDailyReportUseCase の連携を検証
    """
    project_root = get_project_root()
    
    # ViewModelの存在確認
    viewmodel_pattern = project_root / "app/src/main/java/jp/co/screentime/slackreporter"
    viewmodel_files = list(viewmodel_pattern.rglob("*ViewModel.kt"))
    
    if not viewmodel_files:
        return VerificationResult(
            function_id="CF-005",
            scenario_name="手動送信UI実装の存在確認",
            passed=False,
            actual_output=None,
            expected_output="ViewModel が存在",
            error_message="ViewModelファイルが見つかりません",
            interpretation="手動送信のUI層実装が存在しない"
        )
    
    # HomeViewModel or similar
    home_related = [f for f in viewmodel_files if "Home" in f.name or "Main" in f.name]
    
    if not home_related:
        # HomeViewModelがなくても他のViewModelで手動送信があるかチェック
        for vm_file in viewmodel_files:
            content = vm_file.read_text()
            if "sendDailyReportUseCase" in content or "SendDailyReport" in content:
                home_related = [vm_file]
                break
    
    if not home_related:
        return VerificationResult(
            function_id="CF-005",
            scenario_name="手動送信機能の存在確認",
            passed=False,
            actual_output=f"見つかったViewModel: {[f.name for f in viewmodel_files]}",
            expected_output="手動送信機能を持つViewModelが存在",
            error_message="手動送信機能を持つViewModelが見つかりません",
            interpretation="手動送信のUI連携が実装されていない可能性"
        )
    
    # 手動送信機能のチェック
    content = home_related[0].read_text()
    checks = [
        ("SendDailyReportUseCase", "UseCaseの注入"),
    ]
    
    missing = []
    for pattern, description in checks:
        if pattern not in content:
            missing.append(description)
    
    passed = len(missing) == 0
    
    return VerificationResult(
        function_id="CF-005",
        scenario_name="手動送信機能の検証",
        passed=passed,
        actual_output=f"検出ViewModel: {home_related[0].name}",
        expected_output="手動送信機能が実装されている",
        error_message=f"未実装: {missing}" if missing else None,
        interpretation=(
            "手動送信機能が正しく実装されている" if passed
            else f"以下の要素が不足: {', '.join(missing)}"
        )
    )

def verify_test_coverage() -> VerificationResult:
    """
    QA-001: テストカバレッジの確認
    """
    project_root = get_project_root()
    test_dir = project_root / "app/src/test"
    android_test_dir = project_root / "app/src/androidTest"
    
    test_exists = test_dir.exists() and any(test_dir.rglob("*.kt"))
    android_test_exists = android_test_dir.exists() and any(android_test_dir.rglob("*.kt"))
    
    if not test_exists and not android_test_exists:
        return VerificationResult(
            function_id="QA-001",
            scenario_name="テストカバレッジの確認",
            passed=False,
            actual_output="テストコード: 0ファイル",
            expected_output="テストカバレッジ >= 70%",
            error_message="テストコードが存在しません",
            interpretation="テストの追加が最優先で必要です（GAP-001参照）"
        )
    
    test_files = list(test_dir.rglob("*.kt")) if test_dir.exists() else []
    android_test_files = list(android_test_dir.rglob("*.kt")) if android_test_dir.exists() else []
    total_test_files = len(test_files) + len(android_test_files)
    
    return VerificationResult(
        function_id="QA-001",
        scenario_name="テストカバレッジの確認",
        passed=total_test_files > 0,
        actual_output=f"テストファイル: {total_test_files}個",
        expected_output="テストカバレッジ >= 70%",
        interpretation=(
            f"テストが存在します（{total_test_files}ファイル）。カバレッジ計測にはJaCoCo設定が必要です。"
            if total_test_files > 0
            else "テストの追加が必要です"
        )
    )

def main():
    """全Core Functionを検証し、レポートを生成"""
    
    results: List[VerificationResult] = [
        verify_cf001_usage_stats_implementation(),
        verify_cf002_slack_webhook_implementation(),
        verify_cf003_worker_implementation(),
        verify_cf004_exclusion_implementation(),
        verify_cf005_manual_send_implementation(),
        verify_test_coverage(),
    ]
    
    # レポート生成
    print("=" * 60)
    print("CORE FUNCTION VERIFICATION REPORT")
    print("=" * 60)
    
    passed_count = sum(1 for r in results if r.passed)
    total_count = len(results)
    
    for r in results:
        status = "✅ PASS" if r.passed else "❌ FAIL"
        print(f"\n{status} [{r.function_id}] {r.scenario_name}")
        print(f"  実際: {r.actual_output}")
        print(f"  期待: {r.expected_output}")
        print(f"  解釈: {r.interpretation}")
        if r.error_message:
            print(f"  エラー: {r.error_message}")
    
    print("\n" + "=" * 60)
    print(f"SUMMARY: {passed_count}/{total_count} passed")
    
    if passed_count == total_count:
        print("判定: ✅ リポジトリの存在意義が検証された")
    else:
        print("判定: ❌ 存在意義の一部が未達成")
        print("\n次のアクション:")
        for r in results:
            if not r.passed:
                print(f"  - {r.function_id}: {r.interpretation}")
    
    # 結果をJSONで保存
    project_root = get_project_root()
    output_path = project_root / ".audit/output/verification_result.json"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(
        [asdict(r) for r in results],
        ensure_ascii=False, indent=2
    ))
    
    print(f"\n結果を保存しました: {output_path}")
    
    sys.exit(0 if passed_count == total_count else 1)

if __name__ == "__main__":
    main()
